### ISSUE TITLE
Compatibility with PIPseq

### ISSUE THREAD

**Issue by kasperlab** [frisen-lab/TREX#84]
Hi! 
I recently prepared PIPseq (v4) libraries from lentivirus-transfected cells. This includes running the fastq files through pipseeker package for read mapping, where I can get out possorted bam file and count matrixes (raw and filtered), among other output. 
I can also see the reporter (Tomato) expression in the cells, so custom reference works.

Do you have any suggestions on how I could proceed with the existing output to run TREX?

Thanks!
Karl

**Comment by acorbat** [comment]
I might not be the best to reply, but maybe I can give some pointers. Considering that pipseeker's output is a possorted bam file, you could probably use [run10x](https://github.com/frisen-lab/TREX#run-trex). TREX will look for `.bam` files in the provided folder and run the analysis according to the parameters provided. You will have to provide parameters for the chromosome, start and end position of the barcode, etc. In the README you will find a description of other parameters.

If you want/need to delve deeper on what the command is doing, [run_trex](https://github.com/frisen-lab/TREX/blob/34d30aad5991948d6e457d621c0090bac3df6ec3/src/trex/cli/run10x.py#L170) might be a good starting point.

**Comment by karlann** [comment]
I tried to use the run10x function, but I'm getting errors related to the barcode formats (e.g., my cell barcodes didn't end with "-1"). While that was easy to fix for the barcodes.tsv file, should the cell barcodes also end with -1 in the bam file?

Also, currently I'm getting an error that UMIs are not found:


```bash
/mnt/storage/karla/data/lentivirus/pipseq/V350294109/Mapped_reads_LV_BC/LV_11_test/outs$ trex run10x /mnt/storage/karla/data/lentivirus/pipseq/V350294109/Mapped_reads_LV_BC/LV_11_test/ --genome-name GRCm39 --chromosome chrTomato-N --samples LV_11 --delete -s 695 -e 724
Trex 0.4.dev402+g34d30aa
Command line arguments: run10x /mnt/storage/karla/data/lentivirus/pipseq/V350294109/Mapped_reads_LV_BC/LV_11_test/ --genome-name GRCm39 --chromosome chrTomato-N --samples LV_11 --delete -s 695 -e 724
Reading cloneIDs from chrTomato-N:695-724 in /mnt/storage/karla/data/lentivirus/pipseq/V350294109/Mapped_reads_LV_BC/LV_11_test/outs/possorted_genome_bam.bam
Found 0 reads with usable cloneIDs and UMIs. Skipped 154 without cell id, 0 without UMI.
Traceback (most recent call last):
  File "/mnt/storage/karla/mamba/minimamba/envs/trex/bin/trex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/storage/karla/mamba/minimamba/envs/trex/lib/python3.12/site-packages/trex/__main__.py", line 60, in main
    module.main(args)
  File "/mnt/storage/karla/mamba/minimamba/envs/trex/lib/python3.12/site-packages/trex/cli/run10x.py", line 95, in main
    run_trex(
  File "/mnt/storage/karla/mamba/minimamba/envs/trex/lib/python3.12/site-packages/trex/cli/run10x.py", line 201, in run_trex
    reads = dataset_reader.read_all(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/storage/karla/mamba/minimamba/envs/trex/lib/python3.12/site-packages/trex/dataset.py", line 145, in read_all
    assert len(umis) > 0, "No UMIs"
           ^^^^^^^^^^^^^
AssertionError: No UMIs
```


My bam file includes both CB and UB tags, where else could the UMI issue arise from?

```
R21304010020001:20241029155747:V350294109:1:777642:2:6  256     chr1    3120293 0       1S98M   *       0       0       GCCTTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTTCTT    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII     gx:Z:-  gn:Z:-  NH:i:18 HI:i:12 CB:Z:AAACGCGACGGCTGGG UB:Z:TTGTGGAACCTA
```

**Comment by acorbat** [comment]
I'm not the ideal person to check these things (maybe @marcelm could help?).

My first thing to check would be that you can find barcodes in your bam file and that they are in the right chromosome and between the start and end position stated when calling `trex run10x`.

Reading of the alginment fle happens [here](https://github.com/frisen-lab/TREX/blob/34d30aad5991948d6e457d621c0090bac3df6ec3/src/trex/bam.py#L103). It could be what you are mentioning of cloneIDs not ending with `-1` (as stated [here](https://github.com/frisen-lab/TREX/blob/34d30aad5991948d6e457d621c0090bac3df6ec3/src/trex/bam.py#L126)). You could also look into running it with the logger in DEBUG and get a couple more messages.

**Comment by marcelm** [comment]
There seem to be just 154 reads covering the cloneID in chrTomato, and all of these are missing the `CB` tag. To double check, please run:
```
samtools view /mnt/storage/karla/data/lentivirus/pipseq/V350294109/Mapped_reads_LV_BC/LV_11_test/outs/possorted_genome_bam.bam chrTomato-N:695-724
```
(or try first with `-c` to just count the number of reads it would output)

Maybe there are enough reads, pipseeker’s read mapping program doesn’t align them over the cloneID (because it’s a 30 nucleotide long stretch of mismatches). Do you know which program it uses? Of course it could just be the case that there are not enough reads. In the datasets I’m familiar with, the cloneID region has been amplified in order to get a lot more reads. Normal transcriptome data has much lower coverage.
